#!/bin/bash -x

usage () {
    echo -e "\nUSAGE: ./ci login|logout <CLOUD PROVIDER> [debug]\n"
    exit 1
}

[[ -n $2 ]] || usage
[[ -n $3 && $3 == debug ]] && set -x

cd $2
tf_output=$(terraform output) || exit 1
cd - >/dev/null 2>&1

if [[ $1 == login ]]; then
    host=$(echo -e "$tf_output" | awk '/bastion_fqdn/{ print $3 }')
    password=$(echo -e "$tf_output" | awk '/concourse_admin_password/{ print $3 }')

    echo -e "\nCreating SSH tunnel in order to access Concourse."
    ps -ef | awk '/8080:127\.0\.0\.1:8080/{ print $2 }' | sudo xargs kill -15
    ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
        -i $2/bastion-admin-ssh-key.pem bastion-admin@$host \
        -L 8080:127.0.0.1:8080 -N &

    sleep 5
    fly -t local login -k -c http://127.0.0.1:8080 -u admin -p $password
    if [[ $? -ne 0 ]]; then
        echo "ERROR! Unable to login to Concourse using the fly CLI."
        exit 1
    fi

    fly -t local sync >/dev/null 2>&1

    echo -e "\nThe Concourse UI is available via the following URL: http://127.0.0.1:8080\n"

elif [[ $1 == logout ]]; then
    ps -ef | awk '/8080\:127\.0\.0\.1\:8080/{ print $2 }' | sudo xargs kill -15

else
    echo -e "\nUSAGE: ./cf_login login|logout <CLOUD PROVIDER>\n"
    exit 1
fi
