#!/bin/bash

set -exo pipefail

SCRIPT_HOME=$(cd $(dirname "$(ls -l $0 | awk '{ print $NF }')") && pwd)
source $SCRIPT_HOME/common

[[ ! -e /root/.docker_installed ]] || exit 0

#
# Configure Docker daemon
#

systemctl enable docker
set +e

if [[ -n $config_server_docker_mount_path ]]; then

  i=0
  mount | grep " $config_server_docker_mount_path " >/dev/null 2>&1
  while [[ $i -lt 12 && $? -ne 0 ]]; do
    echo "Waiting for docker root mount '$config_server_docker_mount_path' to become available..."
    sleep 5
    i=$(($i+1))
    mount | grep " $config_server_docker_mount_path " >/dev/null 2>&1
  done
  if [[ $i -lt 12 ]]; then
    echo "Changing docker root path to '$config_server_docker_mount_path'."

    systemctl stop docker

    mkdir -p /etc/systemd/system/docker.service.d
    cat << ---EOF > /etc/systemd/system/docker.service.d/docker.root.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --data-root $config_server_docker_mount_path/docker
---EOF

    systemctl daemon-reload
  else
    echo "Timed out waiting for docker root mount path to become available. No changes will be made to docker root path."
  fi
fi

set -e
systemctl restart docker

set +ex
touch /root/.docker_installed
