#!/bin/bash

set -e

if [[ `whoami` != "root" ]]; then 
  echo -e "\nThis script needs to be run as root.\n"
  exit 1
fi

ipsec_status=$(ipsec statusall | grep 'Security Associations')
num_up=$(echo "$ipsec_status" | sed 's|.*(\([0-9]*\) up, \([0-9]*\) connecting):|\1|')
num_connecting=$(echo "$ipsec_status" | sed 's|.*(\([0-9]*\) up, \([0-9]*\) connecting):|\2|')
num_connected_clients=$((num_up+num_connecting))

mkdir -p /var/log/ipsecvpn
echo $num_connected_clients > /var/log/ipsecvpn/numvpnusers

shutdown_counter=/var/log/ipsecvpn/shutdown_countdown

counter=$([[ -e $shutdown_counter ]] && cat $shutdown_counter || echo 10)
if [[ $num_connected_clients -eq 0 ]]; then
  counter=$((counter-1))
else
  counter=10
fi
if [[ $counter -gt 0 ]]; then
  echo "$counter" > $shutdown_counter
else
  rm $shutdown_counter
  echo $(date +"%Y-%m-%d %H:%M:%S")' Shutting down instance due to inactivity...' >> /var/log/ipsecvpn-status.log
  shutdown now
fi
