#!/bin/bash -x

echo "waiting 180 seconds for cloud-init to finish boot"
timeout 180 /bin/bash -c \
  'until stat /var/lib/cloud/instance/boot-finished 2>/dev/null; do echo waiting ...; sleep 10; done'

if [[ $? -ne 0 ]]; then
  echo "Timed out waiting for cloud-init to complete boot phase."
  exit 1
fi

set -xo pipefail

# If config file provided then use it otherwise 
# it will be read from the meta-data service
[[ ! -e /usr/local/etc/bastion-config.yml ]] || \
  mv /usr/local/etc/bastion-config.yml /usr/local/etc/config.yml

/usr/local/lib/cloud-inceptor/mount_volume 2>&1 \
  | tee -a /var/log/mount_volume.log \
  || echo "ERROR! Script mount_volume exited with error: $?"

/usr/local/lib/cloud-inceptor/configure_users 2>&1 \
  | tee -a /var/log/configure_users.log \
  || echo "ERROR! Script configure_users exited with error: $?"

/usr/local/lib/cloud-inceptor/configure_network 2>&1 \
  | tee -a /var/log/configure_network.log \
  || echo "ERROR! Script configure_network exited with error: $?"

/usr/local/lib/cloud-inceptor/configure_powerdns 2>&1 \
  | tee -a /var/log/configure_powerdns.log \
  || echo "ERROR! Script configure_powerdns exited with error: $?"

/usr/local/lib/cloud-inceptor/configure_smtp 2>&1 \
  | tee -a /var/log/configure_smtp.log \
  || echo "ERROR! Script configure_smtp exited with error: $?"

/usr/local/lib/cloud-inceptor/configure_apache 2>&1 \
  | tee -a /var/log/configure_apache.log \
  || echo "ERROR! Script configure_apache exited with error: $?"

/usr/local/lib/cloud-inceptor/configure_openvpn 2>&1 \
  | tee -a /var/log/configure_openvpn.log \
  || echo "ERROR! Script configure_openvpn exited with error: $?"

/usr/local/lib/cloud-inceptor/configure_ipsecvpn 2>&1 \
  | tee -a /var/log/configure_ipsecvpn.log \
  || echo "ERROR! Script configure_ipsecvpn exited with error: $?"

/usr/local/lib/cloud-inceptor/configure_squidproxy 2>&1 \
  | tee -a /var/log/configure_squidproxy.log \
  || echo "ERROR! Script configure_squidproxy exited with error: $?"

/usr/local/lib/cloud-inceptor/configure_docker 2>&1 \
  | tee -a /var/log/configure_docker.log \
  || echo "ERROR! Script configure_docker exited with error: $?"

/usr/local/lib/cloud-inceptor/configure_concourse 2>&1 \
  | tee -a /var/log/configure_concourse.log \
  || echo "ERROR! Script configure_concourse exited with error: $?"

chmod 0600 /var/log/configure_*.log
chmod 0600 /var/log/cloud-init*.log
touch /usr/local/etc/.init_instance_complete
