#!/bin/bash

rm -rf /var/lib/apt/lists/*
echo "waiting 180 seconds for cloud-init to update /etc/apt/sources.list"
timeout 180 /bin/bash -c \
  'until stat /var/lib/cloud/instance/boot-finished 2>/dev/null; do echo waiting ...; sleep 1; done'

set -xeu

echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg|apt-key add -
echo "deb http://build.openvpn.net/debian/openvpn/release/2.4 $(lsb_release -c -s) main" > /etc/apt/sources.list.d/openvpn.list

# Update and upgrade the distribution
apt-get update
apt-get -y \
  --allow-downgrades --allow-remove-essential --allow-change-held-packages \
  dist-upgrade

# Install pre-req packages
apt-get install -y \
  pkg-config cmake build-essential \
  openssl libcurl4-openssl-dev libssl-dev \
  libxml2 libxml2-dev \
  pinentry-curses xclip \
  git-core ipcalc

# Disable sshguard if it is installed
apt-get install -y -q \
  --allow-downgrades \
  --allow-remove-essential \
  --allow-change-held-packages \
  sshguard

systemctl stop sshguard
systemctl disable sshguard

# DHCP
apt-get install -y -q \
  --allow-downgrades \
  --allow-remove-essential \
  --allow-change-held-packages \
  isc-dhcp-server

systemctl stop isc-dhcp-server.service
systemctl disable isc-dhcp-server.service
systemctl stop isc-dhcp-server6.service
systemctl disable isc-dhcp-server6.service

# NTP
apt-get install -y -q \
  --allow-downgrades \
  --allow-remove-essential \
  --allow-change-held-packages \
  ntp

# PowerDNS
apt-get install -y -q \
  --allow-downgrades \
  --allow-remove-essential \
  --allow-change-held-packages \
  pdns-server pdns-backend-sqlite3

systemctl stop pdns.service
systemctl disable pdns.service

# Need give some time for PDNS service to
# stop otherwise recursor install fails
sleep 5

apt-get install -y -q \
  --allow-downgrades \
  --allow-remove-essential \
  --allow-change-held-packages \
  pdns-recursor

systemctl stop pdns-recursor.service
systemctl disable pdns-recursor.service

# Docker
curl -fsSL https://get.docker.com/gpg | sudo apt-key add -
curl -fsSL https://get.docker.com/ | sh

usermod -aG docker ubuntu

systemctl stop docker
systemctl disable docker

# OpenVPN
apt-get install -y whois openvpn easy-rsa libpam-google-authenticator zip
systemctl stop openvpn
systemctl disable openvpn

tblk_version="3.7.9a_build_5321"
openvpn_version="2.4.7-I607"

mkdir -p /var/lib/openvpn/clients
curl -L https://tunnelblick.net/release/Tunnelblick_${tblk_version}.dmg \
  -o /var/lib/openvpn/clients/tunnelblick_osx.dmg
curl -L https://swupdate.openvpn.org/community/releases/openvpn-install-${openvpn_version}-Win7.exe \
  -o /var/lib/openvpn/clients/openvpn-install-win7.exe
curl -L https://swupdate.openvpn.org/community/releases/openvpn-install-${openvpn_version}-Win10.exe \
  -o /var/lib/openvpn/clients/openvpn-install-win10.exe
curl -L https://swupdate.openvpn.org/community/releases/openvpn-install-${openvpn_version}-I603.exe \
  -o /var/lib/openvpn/clients/openvpn-install-winsvr2016.exe

# Apache Web Server
apt-get install -y apache2 apache2-utils libapache2-mod-authnz-external pwauth
systemctl stop apache2
systemctl disable apache2

# SMTP
apt-get install -y postfix libsasl2-modules postfix-policyd-spf-python mailutils
systemctl stop postfix
systemctl disable postfix

# Squid Proxy
apt-get install -y squid3
systemctl stop squid
systemctl disable squid

# Docker Compose CLI
docker_compose_version=1.24.1

curl -L https://github.com/docker/compose/releases/download/${docker_compose_version}/docker-compose-`uname -s`-`uname -m` \
  -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Install Bosh CLI
bosh_version=6.0.0

curl -L https://github.com/cloudfoundry/bosh-cli/releases/download/v${bosh_version}/bosh-cli-${bosh_version}-linux-amd64 \
  -o /usr/local/bin/bosh
chmod +x /usr/local/bin/bosh

set +xe
