#!/bin/bash

set -xe

echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg|apt-key add -
echo "deb http://build.openvpn.net/debian/openvpn/release/2.4 $(lsb_release -c -s) main" > /etc/apt/sources.list.d/openvpn.list

# Update and upgrade the distribution
apt-get update
apt-get -y \
    --allow-downgrades --allow-remove-essential --allow-change-held-packages \
    dist-upgrade

apt-get install -y -q \
   ipcalc

# Disable sshguard if it is installed
if [[ -e /etc/sshguard/ ]]; then
    systemctl stop sshguard
    systemctl disable sshguard
fi

# DHCP
apt-get install -y -q \
    --allow-downgrades \
    --allow-remove-essential \
    --allow-change-held-packages \
    isc-dhcp-server

systemctl stop isc-dhcp-server.service
systemctl disable isc-dhcp-server.service
systemctl stop isc-dhcp-server6.service
systemctl disable isc-dhcp-server6.service

# NTP
apt-get install -y -q \
    --allow-downgrades \
    --allow-remove-essential \
    --allow-change-held-packages \
    ntp

# PowerDNS
apt-get install -y -q \
    --allow-downgrades \
    --allow-remove-essential \
    --allow-change-held-packages \
    pdns-server pdns-backend-sqlite3

systemctl stop pdns.service
systemctl disable pdns.service

# Need give some time for PDNS service to
# stop otherwise recursor install fails
sleep 5

apt-get install -y -q \
    --allow-downgrades \
    --allow-remove-essential \
    --allow-change-held-packages \
    pdns-recursor

systemctl stop pdns-recursor.service
systemctl disable pdns-recursor.service

# Docker
curl -fsSL https://get.docker.com/gpg | sudo apt-key add -
curl -fsSL https://get.docker.com/ | sh

usermod -aG docker ubuntu

systemctl stop docker
systemctl disable docker

# OpenVPN
apt-get install -y whois openvpn easy-rsa libpam-google-authenticator zip
systemctl stop openvpn
systemctl disable openvpn

mkdir /usr/lib/openvpn/clients
curl -L https://swupdate.openvpn.org/community/releases/openvpn-install-2.4.5-I601.exe \
    -o /usr/lib/openvpn/clients/openvpn-install-2.4.5-I601.exe

# Apache Web Server
apt-get install -y apache2 apache2-utils libapache2-mod-authnz-external pwauth
systemctl stop apache2
systemctl disable apache2

# SMTP
apt-get install -y postfix libsasl2-modules postfix-policyd-spf-python mailutils
systemctl stop postfix
systemctl disable postfix

# Squid Proxy
apt-get install -y squid3
systemctl stop squid
systemctl disable squid

# Docker Compose CLI
curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` \
    > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Install packages necessary to compile git-crypt and lastpass cli
apt-get install -y \
    pkg-config cmake build-essential \
    openssl libcurl4-openssl-dev libssl-dev \
    libxml2 libxml2-dev \
    pinentry-curses xclip 

# Install git crypt
git clone https://github.com/AGWA/git-crypt /tmp/git-crypt
cd /tmp/git-crypt

make
make install PREFIX=/usr/local

cd -

# # Install lastpass cli
# git clone https://github.com/lastpass/lastpass-cli.git /tmp/lastpass-cli
# cd /tmp/lastpass-cli

# # Checkout the latest tag
# git fetch --tags
# latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
# git checkout $latestTag

# make
# make install PREFIX=/usr/local

# cd -x

# Install Bosh CLI
curl -Lo /usr/local/bin/bosh https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-5.1.2-linux-amd64
chmod +x /usr/local/bin/bosh

set +xe
